CREATE DATABASE customer;
USE customer;

SHOW TABLES;

SELECT * 
FROM customers_cleaned
LIMIT 5;

-- Q1: What is the total revenue generated by male vs female?

SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customers_cleaned
GROUP BY gender;

-- Q2: Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,
       purchase_amount
FROM customers_cleaned
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customers_cleaned
  );

-- Q3: Which are the top 5 products with the highest average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customers_cleaned
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4: Compare the average purchase amounts between Standard and Express shipping.

SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customers_cleaned
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5: Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       COUNT(customer_id) AS total_customers,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers_cleaned
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6: Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           * 100.0 / COUNT(*), 2
       ) AS discount_rate
FROM customers_cleaned
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7: Segment customers into New, Returning, and Loyal
-- based on their previous purchases.

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases <= 1 THEN 'NEW'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
               ELSE 'LOYAL'
           END AS customer_segment
    FROM customers_cleaned
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q8: What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders,
           DENSE_RANK() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS item_rank
    FROM customers_cleaned
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9: Are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?

SELECT subscription_status,
       COUNT(*) AS customer_count,
       ROUND(
           COUNT(*) * 100.0 /
           (SELECT COUNT(*)
            FROM customers_cleaned
            WHERE previous_purchases > 5),
           2
       ) AS percentage
FROM customers_cleaned
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10: What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customers_cleaned
GROUP BY age_group
ORDER BY total_revenue DESC;
